spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauthdb?useUnicode=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always